export const DATA = [
    {
        id: 0,
        image: 'https://storum.ru/image/cache/products/363035-800x800.jpg',
        title: 'Бонпари',
        description: 'Мармелад Бонпари в упаковке',
        composition: ['сироп глюкозы', 'сахар', 'загуститель (желатин)', 'яблочный сок'],
        calorie: 387,
    },
    {
        id: 1,
        image: 'https://img.akusherstvo.ru/images/magaz/im1105862.jpg',
        title: 'Мамба',
        description: 'Фрумеладки Мамба, что бы это не значило',
        composition: ['сироп глюкозы', 'сахар', 'загуститель (желатин)', 'виноградный сок'],
        calorie: 333,
    },
    {
        id: 2,
        image: 'https://piratmarmelad.ru/catalog/product/marmelad-vegan-kislaya-klubnika-w800-h800.jpg',
        title: 'Кислая клубника',
        description: 'Мармелад со вкусом клубники в кислой посыпке',
        composition: ['сироп глюкозы', 'сахар', 'загуститель (желатин)', 'клубничный сок'],
        calorie: 346,
    },
    {
        id: 3,
        image: 'https://static.1000.menu/img/content/21290/-marmelad-domashnii-domashnii-marmelad-iz-klubniki_1499728086_1_max.jpg',
        title: 'Сладкая смородина',
        description: 'Мармелад со вкусом сладкой красной смородины, в балдёжной сахарной посыпке',
        composition: ['сироп глюкозы', 'сахар', 'загуститель (желатин)', 'смородина'],
        calorie: 377,
    },
    {
        id: 4,
        image: 'https://n1s1.hsmedia.ru/3f/2f/71/3f2f71ab6311ec8d8a0a8cd6e8e12b53/728x526_1_a171defad1fb6b4ced11e1498be91dc8@2037x1472_0xac120003_3471390891583422181.jpg',
        title: 'Мишки',
        description: 'Мармеладные мишки, очень вкусные должны быть',
        composition: ['сироп глюкозы', 'сахар', 'загуститель (желатин)', 'яблочный сок'],
        calorie: 402,
    },
    {
        id: 5,
        image: 'https://berezka-land.com/wa-data/public/shop/products/95/32/3295/images/3760/3760.970.jpg',
        title: 'Апельсиновые дольки',
        description: 'Мармелад похожий на дольки апельсина, выглядят балдёжно, на вкус балдёжно, да и по сути тоже балдёжно',
        composition: ['сироп глюкозы', 'сахар', 'загуститель (желатин)', 'много соков'],
        calorie: 387,
    },
];